name: Build 🛠️

on: 
  push:
    branches:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
    
      matrix:
        projectPath:
          - moonshot-challenge
    
        unityVersion:
          - 2019.4.13f1
    
        targetPlatform:
          # - StandaloneOSX
          - StandaloneWindows64
          # - StandaloneLinux64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
    
      - name: Setup cache
        uses: actions/cache@v2.1.2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
    
      - name: Build project
        uses: webbertakken/unity-builder@v1.5
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: MoonShot-${{ matrix.targetPlatform }}
    
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: MoonShot-${{ matrix.targetPlatform }}
          path: build
